### ISSUE TITLE
Drag the words -content type does not show Retry button in IE11 browser

### ISSUE THREAD

**Issue by hirvota** [h5p/h5p-drag-text#14]
Drag the words -content type  does not show Retry button after a wrong answer in IE11 browser.   This is experienced both in Moodle environment with Moodle plugin versions 1.1 and  1.2 and in  H5P.org environment.

**Comment by hirvota** [comment]
In addition to previous description Drag the words doesn't show any score when answering in IE11 browser.  The user does not receive any score even in case all the answers were correct, there appears only Check-box also in this case.

**Comment by Jarvil** [comment]
Strange that developers don't test first with Internet Exlorer 11 and then with other browsers.

**Comment by falcon-git** [comment]
It is indeed strange. It supposedly was tested in IE11, but the test must have been very rough in that case.

I opened a high priority issue for getting it hotfixed here: https://h5ptechnology.atlassian.net/browse/HFP-1070

**Comment by fnoks** [comment]
This issue is resolved and released in H5P.DragText 1.5.7. Available through the H5P content type HUB.

**Comment by falcon-git** [comment]
Good, thank you for reporting this @hirvota

**Comment by hirvota** [comment]
Thank you for quick solution!
