### ISSUE TITLE
Null-letters are removed from the question

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-drag-text#20]
Hello,

There is a bug in Drag Text (1.6.8) -library, this affect moodle mod_hvp 1.5 and h5p.org itself. If Drag text contains letters NULL they are removed, this is unwanted since at least in Finnish language letters null are used often.  @fnoks 

![drag](https://user-images.githubusercontent.com/15193418/32824654-6c37a8c0-c9ea-11e7-99ef-4983b6c04c09.PNG)

![drag2](https://user-images.githubusercontent.com/15193418/32824659-6f88ddf0-c9ea-11e7-90ac-b6534bd2f8ff.PNG)

**Comment by fnoks** [comment]
Thanks for letting us know.

This has now been fixed in code, and I hope to be able to test and release it today!

**Comment by fnoks** [comment]
This is now released!

**Comment by Jarvil** [comment]
Thank you for the quick fix, working as intended 👍
